# Generated by Django 4.0.4 on 2022-09-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre Completo')),
                ('nacionalidad', models.CharField(max_length=200, verbose_name='Nacionalidad')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('fecha_registro', models.DateField(auto_now=True, verbose_name='Fecha Registro')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True, unique=True, verbose_name='Nombre')),
                ('fecha_registro', models.DateField(auto_now=True, verbose_name='Fecha Registro')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreedi', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('fecha_registro', models.DateField(auto_now=True, verbose_name='Fecha Registro')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'ordering': ['nombreedi'],
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, null=True, unique=True, verbose_name='Nombre')),
                ('fecha_registro', models.DateField(auto_now=True, verbose_name='Fecha Registro')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60, unique=True, verbose_name='Titulo')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad o Stock')),
                ('fechapublicacion', models.DateField(verbose_name='Fecha de publicacion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='libro/%Y/%m/%d')),
                ('fecha_registro', models.DateField(auto_now=True, verbose_name='Fecha Registro')),
                ('autor', models.ManyToManyField(to='libro.autor')),
                ('categoria', models.ManyToManyField(to='libro.categoria')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.editorial')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.idioma')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
    ]
