# Generated by Django 4.0.4 on 2022-09-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorial',
            options={'ordering': ['id'], 'verbose_name': 'Editorial', 'verbose_name_plural': 'Editoriales'},
        ),
        migrations.AlterField(
            model_name='autor',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'otro')], default='F', max_length=1),
        ),
    ]
