# Generated by Django 3.2.2 on 2022-11-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20221031_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='entregada',
            field=models.BooleanField(default=False, verbose_name='entregada'),
        ),
    ]
