# Generated by Django 4.0.4 on 2022-10-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_vencimiento',
        ),
    ]
