# Generated by Django 3.2.2 on 2022-11-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
